/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class KonversiSuhu extends javax.swing.JFrame {
   
    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        Group2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        celcius1 = new javax.swing.JRadioButton();
        fahrenheit1 = new javax.swing.JRadioButton();
        calvin1 = new javax.swing.JRadioButton();
        celcius2 = new javax.swing.JRadioButton();
        fahrenheit2 = new javax.swing.JRadioButton();
        calvin2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        jLabel1.setText("Input");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("To");

        Group2.add(celcius1);
        celcius1.setText("Celcius");
        celcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celcius1ActionPerformed(evt);
            }
        });

        Group2.add(fahrenheit1);
        fahrenheit1.setText("Fahrenheit");

        Group2.add(calvin1);
        calvin1.setText("Calvin");

        Group1.add(celcius2);
        celcius2.setText("Celcius");

        Group1.add(fahrenheit2);
        fahrenheit2.setText("Fahrenheit");

        Group1.add(calvin2);
        calvin2.setText("Calvin");
        calvin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calvin2ActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(celcius1)
                            .addComponent(fahrenheit1)
                            .addComponent(calvin1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fahrenheit2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(celcius2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(calvin2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celcius1)
                    .addComponent(celcius2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fahrenheit1)
                    .addComponent(fahrenheit2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calvin1)
                    .addComponent(calvin2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celcius1ActionPerformed

    private void calvin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calvin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calvin2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    double nilai;
    float hasil;
    String output;
    
    nilai=Double.valueOf(txtField.getText());
        if(celcius1.isSelected())
        {
            if(celcius2.isSelected()){
                hasil = (float) nilai;
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
            if(fahrenheit2.isSelected()){
                hasil = (float) (nilai*1.8+32);
                output = String.valueOf(hasil);
                txtResult.setText(output);
            }
            if(calvin2.isSelected()){
                hasil = (float) (nilai+273.15);
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
        }
        else if(fahrenheit1.isSelected()){
            if(fahrenheit2.isSelected()){
                hasil = (float) nilai;
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
            if (celcius2.isSelected()){
                hasil = (float) (nilai-32)*5/9;
                output = String.valueOf(hasil);
                txtResult.setText(output);
            }
            if(calvin2.isSelected()){
                hasil = (float) (nilai+459.67/1.8);
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
        }
        else if(calvin1.isSelected()){
            if(calvin2.isSelected()){
                hasil = (float) nilai;
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
            if(celcius2.isSelected()){
                hasil = (float) (nilai-273.15);
                output=String.valueOf(hasil);
                txtResult.setText(output);
            }
            if(fahrenheit2.isSelected()){
                hasil = (float) (nilai*1.8-459.67);
                output=String.valueOf(hasil);
                txtResult.setText(output);
                
            }
            
            
            }
        
            
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Group1;
    private javax.swing.ButtonGroup Group2;
    private javax.swing.JRadioButton calvin1;
    private javax.swing.JRadioButton calvin2;
    private javax.swing.JRadioButton celcius1;
    private javax.swing.JRadioButton celcius2;
    private javax.swing.JRadioButton fahrenheit1;
    private javax.swing.JRadioButton fahrenheit2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtField;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
